<?php
/**
 * An array that contains varios system messages
 * The First to digets in the array identify the message type
 *
 *   This program is free software; you can redistribute it and/or modify  
 *   it under the terms of the GNU General Public License as published by  
 *   the Free Software Foundation; either version 2 of the License, or     
 *   (at your option) any later version.                                   
 *                                                                         
 *   This program is distributed in the hope that it will be useful,       
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
 *   GNU General Public License for more details.                          
 *                                                                         
 *   You should have received a copy of the GNU General Public License     
 *   along with this program; if not, write to the                         
 *   Free Software Foundation, Inc.,                                      
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.   
 *
 *
 * @package JustReason_Engine
 *
 * @author Nial Muecke <nmuecke@justsys.com.au>
 *
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * @copyright Copyright (c) 2007, Nial Muecke
 */

/**
 * 00 general system messages
 * @name $MSG['00??'] 
 * @global array  
 */
$MSG[0000] = "System Message";
$MSG[0001] = "Page not found!";
/**
 * 01 security and access messages
 * @name $MSG['01??'] 
 * @global array
 */
$MSG[0100] = "Security Message";
$MSG[0101] = "User logged in.";
$MSG[0102] = "User not found.";
$MSG[0103] = "Username does not exist.";
$MSG[0104] = "Bad username or password.";
$MSG[0105] = "Please enter you Username.";
$MSG[0106] = "Please enter you Password.";
$MSG[0107] = "You must accept the terms and conditions if you wish to register.";
$MSG[0108] = "You must enter in an email.";
$MSG[0109] = "You must provide a username.";
$MSG[0110] = "You must provide a password.";
$MSG[0111] = "You must retype  password.";
$MSG[0112] = "The E-Mail address you supplyed is not valid.";
$MSG[0113] = "The username you have provided already exists.";
$MSG[0114] = "The passwords do not match.";
$MSG[0115] = "Field should contain letters only.";
$MSG[0116] = "Old password and new password match.";
/**
 * 02 Database messages
 * @name $MSG['02??'] 
 * @global array
 */
$MSG[0200] = "Database Message";
$MSG[0201] = "Error connecting to database";
$MSG[0202] = "Query faild";

/**
 * 03 JustReason Engine messages
 * @name $MSG['03??'] 
 * @global array
 */
$MSG[0300] = "JustReason Engine Messages";


?>
